-- MySQL Script generated by MySQL Workbench
-- Sat Jul  6 13:46:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema comedor_universitario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comedor_universitario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comedor_universitario` DEFAULT CHARACTER SET utf8 ;
USE `comedor_universitario` ;

-- -----------------------------------------------------
-- Table `comedor_universitario`.`Administracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Administracion` (
  `idAdministracion` INT NOT NULL,
  `dep_responsable` VARCHAR(70) NOT NULL,
  `cargo_dep` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ape_paterno` VARCHAR(45) NOT NULL,
  `ape_materno` VARCHAR(45) NOT NULL,
  `telefono` CHAR(12) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Estudiante` (
  `codigoestudiante` INT NOT NULL,
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ape_paterno` VARCHAR(45) NOT NULL,
  `ape_materno` VARCHAR(45) NOT NULL,
  `est_beca` ENUM("Activo", "Inactivo") NOT NULL,
  `tip_beca` ENUM("Becado", "Accesitario") NOT NULL,
  `idAdministracion` INT NOT NULL,
  `idCarrera` INT NOT NULL,
  PRIMARY KEY (`codigoestudiante`),
  INDEX `idAdministracion_idx` (`idAdministracion` ASC) VISIBLE,
  INDEX `idCarrera_idx` (`idCarrera` ASC) VISIBLE,
  CONSTRAINT `idAdministracion`
    FOREIGN KEY (`idAdministracion`)
    REFERENCES `comedor_universitario`.`Administracion` (`idAdministracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCarrera`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `comedor_universitario`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Encuesta` (
  `idEncuesta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `Comentario` VARCHAR(120) NOT NULL,
  `Puntuacion` INT NOT NULL,
  `codigoestudiante2` INT NOT NULL,
  PRIMARY KEY (`idEncuesta`),
  INDEX `codigoestudiante_idx` (`codigoestudiante2` ASC) VISIBLE,
  CONSTRAINT `codigoestudiante2`
    FOREIGN KEY (`codigoestudiante2`)
    REFERENCES `comedor_universitario`.`Estudiante` (`codigoestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Asistencia` (
  `idAsistencia` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `codigoestudiante1` INT NOT NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `codigoestudiante_idx` (`codigoestudiante1` ASC) VISIBLE,
  CONSTRAINT `codigoestudiante1`
    FOREIGN KEY (`codigoestudiante1`)
    REFERENCES `comedor_universitario`.`Estudiante` (`codigoestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Concesionaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Concesionaria` (
  `idConcecionaria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `num_telefono` CHAR(12) NOT NULL,
  `nro` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConcecionaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Menu` (
  `idMenu` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `tip_menu` ENUM("Desayuno", "Almuerzo") NOT NULL,
  `idConcecionaria` INT NOT NULL,
  PRIMARY KEY (`idMenu`),
  INDEX `idConcecionaria_idx` (`idConcecionaria` ASC) VISIBLE,
  CONSTRAINT `idConcecionaria`
    FOREIGN KEY (`idConcecionaria`)
    REFERENCES `comedor_universitario`.`Concesionaria` (`idConcecionaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Comida` (
  `idComida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `info_nutricional` VARCHAR(120) NOT NULL,
  `ingredientes` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(70) NOT NULL,
  `idMenu` INT NOT NULL,
  PRIMARY KEY (`idComida`),
  INDEX `idMenu_idx` (`idMenu` ASC) VISIBLE,
  CONSTRAINT `idMenu`
    FOREIGN KEY (`idMenu`)
    REFERENCES `comedor_universitario`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Personal` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ape_paterno` VARCHAR(45) NOT NULL,
  `ape_materno` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `idConcesionaria2` INT NOT NULL,
  PRIMARY KEY (`dni`),
  INDEX `idConcecionaria_idx` (`idConcesionaria2` ASC) VISIBLE,
  CONSTRAINT `idConcesionaria2`
    FOREIGN KEY (`idConcesionaria2`)
    REFERENCES `comedor_universitario`.`Concesionaria` (`idConcecionaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Contrato` (
  `idContrato` INT NOT NULL AUTO_INCREMENT,
  `fecha_fin` VARCHAR(45) NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  `detalles` VARCHAR(45) NOT NULL,
  `est_contrato` ENUM("Activo", "Inactivo") NOT NULL,
  `idConcesionaria1` INT NOT NULL,
  `idAdministracion1` INT NOT NULL,
  PRIMARY KEY (`idContrato`),
  INDEX `idConcecionaria_idx` (`idConcesionaria1` ASC) VISIBLE,
  INDEX `idAdministracion_idx` (`idAdministracion1` ASC) VISIBLE,
  CONSTRAINT `idConcesionaria1`
    FOREIGN KEY (`idConcesionaria1`)
    REFERENCES `comedor_universitario`.`Concesionaria` (`idConcecionaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAdministracion1`
    FOREIGN KEY (`idAdministracion1`)
    REFERENCES `comedor_universitario`.`Administracion` (`idAdministracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Inventario` (
  `idInventario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cant_disponible` INT NOT NULL,
  `fecha_caducidad` DATE NOT NULL,
  `idConcesionaria3` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `idConcecionaria_idx` (`idConcesionaria3` ASC) VISIBLE,
  INDEX `idCategoria_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `idConcesionaria3`
    FOREIGN KEY (`idConcesionaria3`)
    REFERENCES `comedor_universitario`.`Concesionaria` (`idConcecionaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `comedor_universitario`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `nro` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comedor_universitario`.`regis_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comedor_universitario`.`regis_compra` (
  `idregis_compra` INT NOT NULL,
  `cant_comprada` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cost_total` FLOAT NOT NULL,
  `idInventario` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  PRIMARY KEY (`idregis_compra`),
  INDEX `idInventario_idx` (`idInventario` ASC) VISIBLE,
  INDEX `idProveedor_idx` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `idInventario`
    FOREIGN KEY (`idInventario`)
    REFERENCES `comedor_universitario`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `comedor_universitario`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
